# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  PYTHON_VERSION: "3.10"
  RUN_ON: "ubuntu-latest"

permissions:
  contents: read

jobs:
  quality-check:
    runs-on: $RUN_ON
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: $PYTHON_VERSION

    - name: linter
      uses: py-actions/flake8@v2

    - name: format check
      uses: psf/black@stable    

    - name: type check
      uses: jpetrucciani/mypy-check@master
      with: 
        mypy_flags: '--strict'

  test:
    runs-on: $RUN_ON
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: $PYTHON_VERSION
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: install playwright
      run: |
        playwright install
    - name: start flask server
      run: |
        flask run &
    - name: run pytests
      run: |
        pytest
